eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.datasource.url=jdbc:postgresql://user-db:5432/userDB
spring.kafka.bootstrap-servers=kafka:9092

jwt.secretKey=${JWT_SECRET_KEY}
